web:
  image: php-zendserver
  ports:
    - "80:80"
  volumes:
    - ../public_html:/var/www/html/akvan.local/public_html
    - ../storage:/var/www/html/akvan.local/storage    
    - ./akvan_config/config.php://var/www/html/akvan.local/public_html/config.php
    - ./akvan_config/admin/config.php:/var/www/html/akvan.local/public_html/admin/config.php
    - ./apache2/akvan.local.conf:/etc/apache2/sites-enabled/akvan.local.conf 
  links:
    - mysql    
mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_USER: root
    MYSQL_ROOT_PASSWORD: 111 
  volumes:
    - ./mysql_init:/docker-entrypoint-initdb.d
       